apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunecreator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunecreator-app
  template:
    metadata:
      labels:
        app: tunecreator-app
    spec:
      containers:
      - name: tunecreator-app
        image: us-central1-docker.pkg.dev/gen-lang-client-0729539659/tunecreator-repo/tunecreator-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: tunecreator-secrets
              key: GROQ_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: tunecreator-service
spec:
  selector:
    app: tunecreator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer